### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Koch013** [neooblaster/zcl_log_util#18]
Hi,
as I like your zcl_log_util and that you have released it with a good manual including demos, I was wondering if you did not put a licence on this repository on purpose, as this means that no one is allowed to use it:

`If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose`

from [https://choosealicense.com/no-permission/](url)

I'm looking forward to hearing your opinion. 
Thanks.

**Comment by neooblaster** [comment]
Hello @Koch013 ,

I was not aware about this point regarding Licence. 

I like create and share libraries, but indeed, not familiar wih Licences terms.
I thank you for the notification and the link to [https://choosealicense.com/no-permission/](https://github.com/neooblaster/zcl_log_util/issues/url).

I added the simpliest licence : [MIT](https://choosealicense.com/licenses/mit/).
From now, feel free to use / fork the library for your own 😊

Best regards,
Nicolas D.
